name = "ContinuedFractionsLentz"
uuid = "f357a989-9b0f-47dc-aaa1-cd5329a4d1cb"
authors = ["YuttariKanata <yuttarikanata@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
